### ISSUE TITLE
Thanks for the package

### ISSUE THREAD

**Issue by impredicative** [pscosta5/dressup#18]
I just want to say I am [using this package](https://github.com/impredicative/irc-rss-feed-bot/blob/b6361c80ebb89a5c1f8b973221e054a65b237037/ircrssfeedbot/style.py#L24), so thank you for providing it.

**Comment by pscosta5** [comment]
Awesome! That's great to hear @impredicative!

Feel free to leave any feedback if you run into issues or think of improvements!
